 version: 2
 jobs:
    build:
      docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      environment:
      - METEOR_ALLOW_SUPERUSER: true
      steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
      - run: if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
      - run: sudo npm install -g spacejam@1.6.2-rc.1
      - run: sudo npm install -g coffee-script
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - "~/.npm"
            - "~/.meteor"
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "LC_ALL=en_US.UTF-8" >> /etc/environment  
      # run tests!
      - run: npm run test