 version: 2
 jobs:
    build:
      docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      environment:
      - METEOR_ALLOW_SUPERUSER: true
      - ENV LANG: en_US.UTF-8  
      - ENV LANGUAGE: en_US:en  
      - ENV LC_ALL: en_US.UTF-8 
      steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: sudo locale-gen en_US.UTF8
      - run: sudo localedef -i en_US -f UTF-8 en_US.UTF-8
      - run: if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
      - run: if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
      - run: sudo npm install -g spacejam@1.6.2-rc.1
      - run: sudo npm install -g coffee-script
      - run: npm install
      - run: meteor remove kadira:flow-router
      - save_cache:
          paths:
            - node_modules
            - "~/.npm"
            - "~/.meteor"
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: mkdir ~/mocha
      - run:
          command: spacejam test --driver-package=practicalmeteor:mocha-xunit-reporter --load-images=no --ssl-protocol=TLSv1 --xunit-out ~/mocha/unit-tests.xml
          environment:
            MOCHA_FILE: ~/mocha/test-results.xml
          when: always
      - store_test_results:
          path: ~/mocha
      - store_artifacts:
          path: ~/mocha 